language: node_js
sudo: false
cache:
  directories:
    - node_modules

node_js:
  - "6"

before_install:
  # Update Node.js modules
  - "test ! -d node_modules || npm prune"
  - "test ! -d node_modules || npm rebuild"
after_success:  "npm install coveralls && cat ./coverage/lcov.info | coveralls"
